version: "3.3"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: happyhomepet
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - musiichuk_db:/var/lib/mysql
      - ./db_dump:/docker-entrypoint-initdb.d/
    restart: always
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - 8082:80
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: happyhomepet
volumes:
  musiichuk_db: